use std::{collections::BTreeSet, fs, path::Path};

use rmcp::model::Tool;
use serde_json::Value;

pub fn render_docs(tools: &[Tool]) -> anyhow::Result<String> {
    let mut output = String::new();
    output.push_str("# MCP Tools\n\n");
    output.push_str("<!-- This file is @generated by `cargo run -- generate-docs`. -->\n\n");
    output.push_str("This document describes the public MCP tool contract exposed by\n");
    output.push_str(
        "`obsidian-vault-mcp`. All paths are vault-relative unless stated otherwise. The\n",
    );
    output.push_str("server supports structural section edits as well as read operations.\n\n");

    output.push_str("## Tool Index\n\n");
    output.push_str("| Tool | Description |\n");
    output.push_str("| --- | --- |\n");
    for tool in tools {
        output.push_str(&format!(
            "| `{}` | {} |\n",
            tool.name,
            markdown_table_text(tool.description.as_deref().unwrap_or(""))
        ));
    }
    output.push('\n');

    for tool in tools {
        output.push_str(&format!("## 🔧 `{}`\n\n", tool.name));
        if let Some(description) = &tool.description {
            output.push_str(description);
            output.push_str("\n\n");
        }

        render_schema_section(
            &mut output,
            "Input",
            &Value::Object((*tool.input_schema).clone()),
        );

        match &tool.output_schema {
            Some(schema) => {
                render_schema_section(&mut output, "Output", &Value::Object((**schema).clone()))
            }
            None => output.push_str("_No structured output schema._\n\n"),
        }
    }

    Ok(output)
}

pub fn write_tools_markdown(path: impl AsRef<Path>, content: &str) -> anyhow::Result<()> {
    fs::write(path, content)?;
    Ok(())
}

pub fn check_tools_markdown(path: impl AsRef<Path>, content: &str) -> anyhow::Result<()> {
    let path = path.as_ref();
    let existing = fs::read_to_string(path)?;
    if existing != content {
        return Err(anyhow::anyhow!(
            "{} is out of date; run `cargo run -- generate-docs`",
            path.display()
        ));
    }
    Ok(())
}

fn markdown_table_text(input: &str) -> String {
    input.replace('\n', " ").replace('|', "\\|")
}

fn render_schema_section(output: &mut String, title: &str, schema: &Value) {
    output.push_str(&format!("{title}:\n\n"));
    render_object_table(output, schema, "Field");
    render_nested_types(output, schema);
    output.push('\n');
}

fn render_object_table(output: &mut String, schema: &Value, first_column: &str) {
    let Some(properties) = schema.get("properties").and_then(Value::as_object) else {
        output.push_str(&format!("Type: `{}`\n\n", schema_type(schema)));
        return;
    };
    let required = required_fields(schema);
    output.push_str(&format!(
        "| {first_column} | Type | Required | Description |\n"
    ));
    output.push_str("| --- | --- | --- | --- |\n");
    for (name, property) in properties {
        let description = property
            .get("description")
            .and_then(Value::as_str)
            .unwrap_or("");
        output.push_str(&format!(
            "| `{}` | `{}` | {} | {} |\n",
            markdown_table_text(name),
            markdown_table_text(&schema_type(property)),
            if required.contains(name) { "yes" } else { "no" },
            markdown_table_text(description)
        ));
    }
    output.push('\n');
}

fn render_nested_types(output: &mut String, schema: &Value) {
    let Some(defs) = schema.get("$defs").and_then(Value::as_object) else {
        return;
    };
    if defs.is_empty() {
        return;
    }
    let referenced = referenced_defs(schema, defs);

    output.push_str("Nested types:\n\n");
    for (name, definition) in defs {
        if !referenced.contains(name) {
            continue;
        }
        output.push_str(&format!("### `{}`\n\n", markdown_table_text(name)));
        if let Some(description) = definition.get("description").and_then(Value::as_str) {
            output.push_str(description);
            output.push_str("\n\n");
        }
        if let Some(variants) = tagged_variants(definition) {
            output.push_str("| Variant | Fields |\n| --- | --- |\n");
            for (variant, fields) in variants {
                output.push_str(&format!(
                    "| `{}` | {} |\n",
                    markdown_table_text(&variant),
                    markdown_table_text(&fields.join(", "))
                ));
            }
            output.push('\n');
        } else if let Some(variants) = enum_values(definition) {
            output.push_str("| Value |\n| --- |\n");
            for value in variants {
                output.push_str(&format!("| `{}` |\n", markdown_table_text(&value)));
            }
            output.push('\n');
        } else if definition.get("properties").is_some() {
            render_object_table(output, definition, "Field");
        } else {
            output.push_str(&format!("Type: `{}`\n\n", schema_type(definition)));
        }
    }
}

fn referenced_defs(schema: &Value, defs: &serde_json::Map<String, Value>) -> BTreeSet<String> {
    let mut referenced = BTreeSet::new();
    collect_refs(schema, &mut referenced);

    let mut pending = referenced.iter().cloned().collect::<Vec<_>>();
    while let Some(name) = pending.pop() {
        let Some(definition) = defs.get(&name) else {
            continue;
        };
        let before = referenced.len();
        collect_refs(definition, &mut referenced);
        if referenced.len() > before {
            pending = referenced.iter().cloned().collect();
        }
    }

    referenced
}

fn collect_refs(value: &Value, refs: &mut BTreeSet<String>) {
    match value {
        Value::Object(object) => {
            if let Some(reference) = object.get("$ref").and_then(Value::as_str)
                && let Some(name) = reference.strip_prefix("#/$defs/")
            {
                refs.insert(name.to_string());
            }
            for value in object.values() {
                collect_refs(value, refs);
            }
        }
        Value::Array(values) => {
            for value in values {
                collect_refs(value, refs);
            }
        }
        _ => {}
    }
}

fn required_fields(schema: &Value) -> BTreeSet<String> {
    schema
        .get("required")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter_map(Value::as_str)
        .map(ToOwned::to_owned)
        .collect()
}

fn schema_type(schema: &Value) -> String {
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        return reference
            .strip_prefix("#/$defs/")
            .unwrap_or(reference)
            .to_string();
    }
    if let Some(const_value) = schema.get("const") {
        return literal_type(const_value);
    }
    if let Some(values) = enum_values(schema) {
        return values
            .into_iter()
            .map(|value| format!("\"{value}\""))
            .collect::<Vec<_>>()
            .join(" | ");
    }
    if let Some(types) = schema.get("type").and_then(Value::as_array) {
        return types
            .iter()
            .filter_map(Value::as_str)
            .collect::<Vec<_>>()
            .join(" | ");
    }
    if let Some(type_name) = schema.get("type").and_then(Value::as_str) {
        if type_name == "array" {
            let item_type = schema
                .get("items")
                .map(schema_type)
                .unwrap_or_else(|| "unknown".to_string());
            return format!("{item_type}[]");
        }
        return type_name.to_string();
    }
    if let Some(any_of) = schema.get("anyOf").and_then(Value::as_array) {
        if let Some(variants) = tagged_variant_names(any_of) {
            return variants.join(" | ");
        }
        return union_type(any_of);
    }
    if let Some(one_of) = schema.get("oneOf").and_then(Value::as_array) {
        if let Some(variants) = tagged_variant_names(one_of) {
            return variants.join(" | ");
        }
        return union_type(one_of);
    }
    if schema.get("properties").is_some() {
        return "object".to_string();
    }
    "unknown".to_string()
}

fn union_type(schemas: &[Value]) -> String {
    schemas
        .iter()
        .map(schema_type)
        .collect::<Vec<_>>()
        .join(" | ")
}

fn enum_values(schema: &Value) -> Option<Vec<String>> {
    schema
        .get("enum")
        .and_then(Value::as_array)
        .map(|values| values.iter().map(literal_type).collect::<Vec<_>>())
}

fn tagged_variants(schema: &Value) -> Option<Vec<(String, Vec<String>)>> {
    let variants = schema
        .get("oneOf")
        .or_else(|| schema.get("anyOf"))
        .and_then(Value::as_array)?;
    let mut output = Vec::new();
    for variant in variants {
        let properties = variant.get("properties").and_then(Value::as_object)?;
        let name = variant_name(properties)?;
        let fields = properties
            .iter()
            .filter(|(_, property)| property.get("const").is_none())
            .map(|(name, property)| format!("`{name}: {}`", schema_type(property)))
            .collect();
        output.push((name, fields));
    }
    Some(output)
}

fn tagged_variant_names(schemas: &[Value]) -> Option<Vec<String>> {
    let mut names = Vec::new();
    for schema in schemas {
        let properties = schema.get("properties").and_then(Value::as_object)?;
        names.push(variant_name(properties)?);
    }
    Some(names)
}

fn variant_name(properties: &serde_json::Map<String, Value>) -> Option<String> {
    properties
        .get("status")
        .and_then(|property| property.get("const"))
        .or_else(|| {
            properties
                .values()
                .find_map(|property| property.get("const"))
        })
        .map(literal_type)
}

fn literal_type(value: &Value) -> String {
    match value {
        Value::Null => "null".to_string(),
        Value::Bool(value) => value.to_string(),
        Value::Number(value) => value.to_string(),
        Value::String(value) => value.clone(),
        Value::Array(_) => "array".to_string(),
        Value::Object(_) => "object".to_string(),
    }
}

#[cfg(test)]
mod tests;
